export const MISMATCH_PASSWORD_ERROR = "Passwords must match"
export const INCOMPLETE_FORM_ERROR = "Please complete all form fields"
export const INVALID_EMAIL_FORMAT_ERROR = "Please provide a valid email address"
export const INVALID_PASSWORD_FORMAT_ERROR = "Please provide a valid password"
export const MISSING_EMAIL_ERROR = "Please provide an email"
export const MISSING_PASSWORD_ERROR = "Please provide a password"
export const USER_ALREADY_EXISTS_ERROR = "User already exists. Log in instead."
export const USER_REGISTRATION_SUCCESS = "User successfully registered"