export const MISMATCH_PASSWORD_ERROR = "Passwords must match"
export const INCOMPLETE_FORM_ERROR = "Please complete all form fields"
export const INVALID_EMAIL_FORMAT_ERROR = "Please enter a valid email address"
export const MISSING_EMAIL_ERROR = "Missing email"
export const MISSING_PASSWORD_ERROR = "Missing password"